## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('video-streaming', ['internet', 'csma', 'video-push', 'point-to-point', 'applications'])
    obj.source = 'video-streaming.cc'